# Import

In [124]:
import pandas as pd
import numpy as np
%matplotlib inline

In [213]:
houses_df = pd.read_csv('data/train.csv')

In [237]:
house_bird = houses_df.iloc[:, 1:21]
house_phil= houses_df.iloc[:, 21:41]
house_ray = houses_df.iloc[:, 41:61]
house_ty = houses_df.iloc[:, 61:]

## Missing

In [126]:
missing_cols_count = houses_df.isna().sum(0).sort_values(ascending=False)
print(missing_cols_count[missing_cols_count>0])
print("total number of observations: ", len(houses_df))

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageCond        81
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
BsmtExposure      38
BsmtFinType2      38
BsmtFinType1      37
BsmtCond          37
BsmtQual          37
MasVnrArea         8
MasVnrType         8
Electrical         1
dtype: int64
total number of observations:  1460

#### Drop missing

In [127]:
houses_df = houses_df.loc[:, missing_cols_count < 1000].drop('Id', axis = 1)

# EDA: Tables

In [129]:
houses_obj = pd.DataFrame()
houses_int = pd.DataFrame()
houses_float = pd.DataFrame()

for col in houses_df.columns:
    if houses_df[col].dtype == object:
        houses_obj[col] = houses_df[col]
    if houses_df[col].dtype == int:
        houses_int[col] = houses_df[col]
    if houses_df[col].dtype == float:
        houses_float[col] = houses_df[col]

In [146]:
houses_obj.describe()

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
count,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,...,1460,1460,770,1379,1379,1379,1379,1460,1460,1460
unique,5,2,4,4,2,5,3,25,9,8,...,4,7,5,6,3,5,5,3,9,6
top,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,...,TA,Typ,Gd,Attchd,Unf,TA,TA,Y,WD,Normal
freq,1151,1454,925,1311,1459,1052,1382,225,1260,1445,...,735,1360,380,870,605,1311,1326,1340,1267,1198

In [147]:
houses_float.describe()

       LotFrontage   MasVnrArea  GarageYrBlt
count  1201.000000  1452.000000  1379.000000
mean     70.049958   103.685262  1978.506164
std      24.284752   181.066207    24.689725
min      21.000000     0.000000  1900.000000
25%      59.000000     0.000000  1961.000000
50%      69.000000     0.000000  1980.000000
75%      80.000000   166.000000  2002.000000
max     313.000000  1600.000000  2010.000000

In [145]:
houses_int.describe()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,56.897260,10516.828082,6.099315,5.575342,1971.267808,1984.865753,443.639726,46.549315,567.240411,1057.429452,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,42.300571,9981.264932,1.382997,1.112799,30.202904,20.645407,456.098091,161.319273,441.866955,438.705324,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,20.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,20.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,223.000000,795.750000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,50.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,383.500000,0.000000,477.500000,991.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,70.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,712.250000,0.000000,808.000000,1298.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,190.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,5644.000000,1474.000000,2336.000000,6110.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

# EDA: Visualize

In [159]:
house_ty = houses_df.iloc[:,-21:-1]

In [161]:
house_ty.columns

Index(['FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish',
       'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

### 1 FireplaceQu

This is a categorical variable that we may what to remove 'FireplaceQu' as it has 0.472603 missing values.

In [174]:
house_ty['FireplaceQu'].isnull().sum()/len(house_ty)

0.4726027397260274

### 2 GarageType

In [211]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
house_ty.GarageType

In [191]:
range(len(set(house_ty.GarageType)))

range(0, 7)

In [212]:
le = LabelEncoder()
house_ty[['GarageType']] = le.fit_transform(house_ty[['GarageType']].fillna(0).astype(str))

array([2, 2, 2, ..., 2, 2, 2])

In [203]:
house_ty[house_ty['GarageType'].isna()]

,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
39,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,0,0,0,0,0,0,6,2008,WD,AdjLand
48,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,0,102,0,0,0,0,6,2009,New,Partial
78,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,4,2010,WD,Normal
88,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,0,156,0,0,0,0,10,2009,ConLD,Abnorml
89,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,8,2007,WD,Normal
99,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,352,0,0,0,0,0,400,1,2010,WD,Normal
108,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,0,144,0,0,0,0,8,2007,WD,Normal
125,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,53,0,0,0,0,0,0,6,2006,WD,Normal
127,TA,NaN,NaN,NaN,0,0,NaN,NaN,N,0,0,0,0,0,0,0,6,2007,WD,Normal
140,Po,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,4,2010,ConLI,Normal
148,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,4,2008,WD,Normal
155,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,8,128,0,0,0,0,4,2008,WD,Normal
163,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,4,2007,WD,Normal
165,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,140,0,0,0,0,0,0,9,2008,WD,Normal
198,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,198,30,0,0,0,0,7,2009,WD,Abnorml
210,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,96,0,0,0,0,4,2008,WD,Normal
241,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,58,42,0,0,0,0,0,8,2007,WD,Normal
250,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,263,0,0,0,0,0,450,5,2010,WD,Normal
287,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,6,2006,WD,Normal
291,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,184,0,0,0,0,0,3,2008,WD,Normal
307,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,144,0,0,0,0,0,3,2008,WD,Normal
375,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,3,2009,WD,Normal
386,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,151,0,0,0,0,0,5,2006,WD,AdjLand
393,TA,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,4,2006,WD,Abnorml
431,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,98,0,0,0,0,0,9,2008,ConLD,Abnorml
434,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,88,0,0,0,0,0,0,6,2008,WD,Normal
441,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,9,2008,WD,Normal
464,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,8,2009,WD,Normal
495,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,523,115,0,0,0,0,11,2009,WD,Abnorml
520,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,220,114,210,0,0,0,0,8,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,10,2006,WD,AdjLand
960,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,117,0,0,0,0,0,0,2,2010,WD,Normal
968,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,5,2009,WD,Abnorml
970,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,12,2006,WD,Abnorml
976,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,8,2006,WD,Normal
1009,NaN,NaN,NaN,NaN,0,0,NaN,NaN,P,0,0,138,0,0,0,0,6,2006,WD,Normal
1011,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,5,2010,WD,Normal
1030,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,0,228,0,0,0,0,7,2006,WD,Normal
1038,TA,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,5,2009,WD,Normal
1096,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,136,0,115,0,0,0,0,3,2007,WD,Normal
1123,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,200,0,0,0,0,0,6,2009,WD,Normal
1131,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,28,0,0,0,0,0,9,2007,Oth,Abnorml
1137,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,0,176,0,0,0,0,5,2010,WD,Normal
1143,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,24,0,0,0,0,0,7,2008,WD,Normal
1173,Gd,NaN,NaN,NaN,0,0,NaN,NaN,Y,122,0,0,0,0,0,0,3,2007,WD,Normal
1179,Gd,NaN,NaN,NaN,0,0,NaN,NaN,N,0,36,190,0,0,0,0,4,2006,WD,Normal
1218,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,0,0,0,0,0,0,7,2006,WD,Normal
1219,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,201,0,0,0,0,0,0,4,2006,WD,Abnorml
1234,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,192,0,0,0,0,0,11,2008,WD,Abnorml
1257,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,96,0,0,0,0,0,7,2009,WD,Normal
1283,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,128,0,0,0,0,0,0,4,2010,WD,Normal
1323,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,164,0,0,0,0,0,0,12,2009,WD,Normal
1325,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,0,100,0,0,0,0,1,2008,WD,Normal
1326,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,286,0,0,0,0,5,2007,WD,Normal
1337,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,20,0,0,0,0,0,3,2006,WD,Normal
1349,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,54,20,0,0,0,0,12,2008,WD,Normal
1407,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,3,2009,WD,Normal
1449,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,0,8,2006,WD,Abnorml
1450,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,32,45,0,0,0,0,0,9,2009,WD,Normal
1453,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,36,56,0,0,0,0,0,7,2006,WD,Abnorml